### ISSUE TITLE
Incompatibility with Filth Creates Trash?

### ISSUE THREAD

**Issue by D3nnis3n** [bbradson/Fishery#2]
It seems the mod might have an incompatibility with https://steamcommunity.com/sharedfiles/filedetails/?id=3182399010, after installing Fishery (and while not having Performance Fish active for verification), pawns cleaning floors don't produce trash anymore. Once Fishery is removed, trash is again produced.

Hugslib Logs:
https://gist.github.com/HugsLibRecordKeeper/00c65d6e2c608b1db460d18955faf973

**Comment by bbradson** [comment]
That's not possible. Fishery doesn't run any code by itself. It doesn't even include the usual rimworld mod entry points

**Comment by bbradson** [comment]
The log has 0 references to anything fishery related

**Comment by D3nnis3n** [comment]
Thanks for letting me know, interesting. Only other mod I removed at the same time was Prepatcher, as Fishery was the only mod needing it. I'll see what's going on.

**Comment by D3nnis3n** [comment]
Just for anyone else: It actually turned out that during my test operations "Common Sense" had updated multiple times without me noticing and was causing the failure. It is resolved now.
